const Menu =[
    {
    id: 1,
    image: "https://foodiewish.com/wp-content/uploads/2020/04/Idli-Sambar-Recipe.jpg",
    name: "Idli Sambhar",
    category: "Breakfast",
    price: 25,
    descreption: "I love Idli Sambar ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 2,
    image: "https://www.ruchiskitchen.com/wp-content/uploads/2014/11/Aloo-parantha-recipe.jpg",
    name: "Aloo Parantha",
    category: "Breakfast",
    price: 25,
    descreption: "I love Aloo Parantha Lorem iplit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 3,
    image: "https://www.thespruceeats.com/thmb/iEaMy2Slf2xPL55IaXYCry-PJks=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/grilled-chicken-panini-sandwich-recipe-2097378-hero-01-09e7d3d7e8604a8a90217e6f9e356648.jpg",
    name: "Sandwich",
    category: "Breakfast",
    price: 25,
    descreption: "I love Grilled Sandwich ipsum dolor sit amet tam quam praesentium! Lorem ipsum dolor sit amet.",
},
{
    id: 4,
    image: "https://static.toiimg.com/thumb/63841432.cms?imgsize=1151127&width=509&height=340",
    name: "Dosa",
    category: "Lunch",
    price: 25,
    descreption:"I love Dosa Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 5,
    image: "https://5.imimg.com/data5/HU/PG/OE/SELLER-9770898/special-veg-thali-500x500.jpg",
    name: "Special Thali",
    category: "Lunch",
    price: 25,
    descreption: "I love Thali ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 6,
    image: "https://i0.wp.com/foodtrails25.com/wp-content/uploads/2019/04/img_5604_ezy_watermark_14-04-2019_02-27-00am.jpg?w=1440&ssl=1",
    name: "Biriyani",
    category: "Lunch",
    price: 25,
    descreption: "I love Biriyani Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 7,
    image: "http://www.thegreenchilli.in/wp-content/uploads/2018/01/oreo-shake-recipe-800x500.jpg",
    name: "Oreo Milkshake",
    category: "Drinks",
    price: 25,
    descreption:"I love Dosa Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 8,
    image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/burger-king-vanilla-m-ms-shake-1548171240.jpg?resize=980:*",
    name: "Vanilla Shake",
    category: "Drinks",
    price: 25,
    descreption: "I love Vanilla Shake ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 9,
    image: "https://www.thespruceeats.com/thmb/zx7iXm5MQY7Y0ef0BZ2D6a2Q7mI=/940x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/holiday-pomegranate-mojito-recipe-760346-hero-3baad7c00ac743328d74be3b9f03f372.jpg",
    name: "Mocktail",
    category: "Drinks",
    price: 25,
    descreption: "I love Mocktail Drink Lorem ipsum dolor sit amet . Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 10,
    image: "https://i1.wp.com/vegecravings.com/wp-content/uploads/2020/01/Vegetable-Masala-Maggi-Recipe-Step-By-Step-Instructions-scaled.jpg?resize=1024%2C900&quality=65&strip=all&ssl=1",
    name: "maggi",
    category: "Snacks",
    price: 25,
    descreption:"I love Maggi Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 11,
    image: "https://5.imimg.com/data5/SELLER/Default/2021/8/NB/VF/IU/125386639/paneer-masala-cheesy-roll1-500x500.jpg",
    name: "Panner Roll",
    category: "Snacks",
    price: 25,
    descreption: "I love Roll Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 12,
    image: "https://cdn.booktou.in/assets/image/store/bin_279/prim_3840411638891846.jpeg",
    name: "Fried Momos",
    category: "Snacks",
    price: 25,
    descreption:"I love Momos Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 13,
    image: "https://www.vidhyashomecooking.com/wp-content/uploads/2018/04/VegHakkaNoodlesStep-5.jpg",
    name: "Hakka Noddles",
    category: "Dinner",
    price: 25,
    descreption:"I love Noodles Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 14,
    image: "https://static.toiimg.com/thumb/52416693.cms?imgsize=789478&width=509&height=340",
    name: "Pav Bhaji",
    category: "Dinner",
    price: 25,
    descreption:"I love Pav Bhaji ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 15,
    image: "https://i.cdn.newsbytesapp.com/images/l198_38181592397420.jpg",
    name: "Chole Bhature",
    category: "Dinner",
    price: 25,
    descreption:"I love Chole Bhature Lorem ipsum dolor consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 16,
    image: "https://tajsweetsandnamkeen.com/wp-content/uploads/2021/05/gulab-jamun.jpg",
    name: "Gulab Jamun",
    category: "Desert",
    price: 25,
    descreption:"I love Gulab Jamun Lorem ipsum dolor sit amet consectetur adipisicing elit. error totam quam praesentium!",
},
{
    id: 17,
    image: "https://www.pbs.org/food/wp-content/blogs.dir/2/files/2014/05/molten-lava-cake-feature.jpg",
    name: "Choco Lava",
    category: "Desert",
    price: 25,
    descreption:"I love Choco Lava ipsum dolor sit amet consectetur adipisicing elit. Nisi consequuntur facilis error totam quam praesentium!",
},
{
    id: 18,
    image: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ae3qqfev6j7hzhxw6if3",
    name: "Ice-Cream",
    category: "Desert",
    price: 25,
    descreption:"I love Ice-Cream Lorem ipsum dolor sit amet . Nisi consequuntur facilis error totam quam praesentium!",
},
];
export default Menu;